version: "3.2"
networks:
  datingapp:

services:
  frontendapp:
    build:
      context: ./../../DatingApp-SPA
      dockerfile: ./../deployment/dev/Dockerfile.dev.frontend
    volumes:
      - ./../../DatingApp-SPA:/app/
    networks:
      - datingapp
    ports:
      - "4200:4200"
    stdin_open: true # docker run -i
    tty: true # docker run -t

  backendapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - DOTNET_ENVIRONMENT=development
    build:
      context: ./../..
      dockerfile: ./deployment/dev/Dockerfile.dev.backend
    volumes:
      - ./../..:/app
      - /app/DatingApp/bin/
      - /app/DatingApp/obj/
    networks:
      - datingapp
    ports:
      - "5000:5000"
    stdin_open: true # docker run -i
    tty: true # docker run -t
    
  datingdb:
    image: mysql
    container_name: datingdb
    networks:
      - datingapp
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./../database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql
      - ./../database_dump.sql:/docker-entrypoint-initdb.d/database_dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: example
