version: "3.1"
networks:
  datingapp:
services:
  datingdb:
    build:
      context: ./../..
      dockerfile: ./deployment/prod/Dockerfile.prod.database
    container_name: datingappdb_container
    #TODO: ports should not be open in production
    ports:
      - "3306:3306"
    networks:
      - datingapp

  backend:
    build:
      context: ./../..
      dockerfile: ./deployment/prod/Dockerfile.prod.backend
    container_name: datingappbackend_container
    # ports:
    #   - "5000:5000"
    networks:
      - datingapp
    stdin_open: true # docker run -i
    tty: true # docker run -t

  frontend:
    build:
      context: ./../..
      dockerfile: ./deployment/prod/Dockerfile.prod.frontend
    container_name: datingappfrontend_container
    ports:
      - "80:80"
    networks:
      - datingapp
    volumes: 
      - ./nginx_local.conf:/etc/nginx/conf.d/default.conf