version: "3.1"
networks:
  datingapp:
services:
  frontend:
    build:
      context: ./../..
      dockerfile: ./deployment/prod/Dockerfile.prod.frontend
    container_name: datingappfrontend_container
    ports:
      - "80:80"
    networks:
      - datingapp
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  backend:
    build:
      context: ./../..
      dockerfile: ./deployment/prod/Dockerfile.prod.backend
    container_name: datingappbackend_container
    networks:
      - datingapp

  datingdb:
    build:
      context: ./../..
      dockerfile: ./deployment/prod/Dockerfile.prod.database
    container_name: datingappdb_container
    networks:
      - datingapp


