version: "3.1"
networks:
  frontendDating:
services:
  db:
    image: mysql
    container_name: datingdb
    networks:
      - frontendDating
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: example
  app:
    image: mcr.microsoft.com/dotnet/core/sdk:3.0
    container_name: datingapp
    networks:
      - frontendDating
    ports: 
      - "5000:5000"
