name: deploy
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      - name: Test
        run: echo $GITHUB_SHA_SHORT
        # - uses: arwynfr/actions-docker-context@v2
        #   with:
        #     docker_host: "ssh://root@${{ secrets.DIGITALOCEAN_SSH_HOST }}"
        #     context_name: "dev-server"
        #     ssh_cert: ${{ secrets.DIGITALOCEAN_PUB_SSH_KEY }}
        #     ssh_key: ${{ secrets.DIGITALOCEAN_PRIV_SSH_KEY }}

        # - run: docker --context dev-server container run -p 80:80 nginx
