name: deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_SSH_HOST }}
        username: "root"
        key: ${{secrets.DIGITALOCEAN_PRIV_SSH_KEY}}
        script: docker container run -d -p 80:80 nginx
    # steps:
    #   - name: Set env
    #     run: echo ::set-env name=DOCKER_HOST::ssh://root@${{ secrets.DIGITALOCEAN_SSH_HOST }}
    #   - name: Test
    #     run: echo $DOCKER_HOST
